# ~/.bash_aliases: Contains all the aliases used in bash
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias octave-cli='octave-cli -q'
alias npp='notepad-plus-plus'
alias battery='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E --color=never "state|to\ full|to\ empty|percentage"'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias for Apostrophe as it is a flatpak app
alias apostrophe='flatpak run org.gnome.gitlab.somas.Apostrophe'
alias desmume='flatpak run org.desmume.DeSmuME'
alias bookworm="flatpak run com.github.babluboy.bookworm"

# Alias for user env-preserving sudo
alias presudo='sudo -E env "PATH=$PATH"'

# Easy alias for exo-open
alias eopen='exo-open'

# Aliases for cd'ing into directories
alias qkr='cd ~/Documents/QuantumKickedRotor && conda activate rmt'
alias fock='cd ~/Documents/Localisation/fockspace && conda activate coupling'
alias mbl='cd ~/Documents/SOMBL && codium .'
