# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

PS4='+ $(date "+%s.%N")\011 '

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

# Save the default term in PS_DEFAULT and set alternative term
PS_DEFAULT="$PS1"

# With blue $ prompt
#PS1="\[\e[0;36m\]\$\[\e[m\] "

# With light green $ prompt
PS1="\[\e[1;32m\]\$\[\e[m\] "

# With purple $ prompt
#PS1="\[\e[1;35m\]\$\[\e[m\] "

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Set all the required paths
if [ -f "$HOME/.setpath" ]; then
    source "$HOME/.setpath"
fi

# Set PYTHONPATH
export PYTHONPATH=".:$PYTHONPATH"

# Set default editor to vim
export EDITOR="vim"


# . "$HOME/.cargo/env"

# Setting the env vars for Intel MKL / oneAPI
# . /opt/intel/oneapi/setvars.sh > /dev/null
# export GEM_HOME=$(ruby -e 'puts Gem.user_dir')

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/users/achincholi/Documents/CodeEnvs/Python/Miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/users/achincholi/Documents/CodeEnvs/Python/Miniconda/etc/profile.d/conda.sh" ]; then
        . "/users/achincholi/Documents/CodeEnvs/Python/Miniconda/etc/profile.d/conda.sh"
    else
        export PATH="/users/achincholi/Documents/CodeEnvs/Python/Miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gcr/ssh"
# export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/keyring/ssh"

if pgrep -u "$USER" gcr-ssh-agent > /dev/null; then
    killall gcr-ssh-agent
fi

# Run ssh-agent if not already running
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 8h > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! -f "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi
