#!/bin/sh

# Set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ]; then
    PATH="$HOME/bin:$PATH"
fi

# Set PATH so it includes user's private bin if it exists
if [ -d "$HOME/local/bin" ]; then
    PATH="$HOME/local/bin:$PATH"
fi

# Add AppImage Applications to PATH
if [ -d "$HOME/Applications" ]; then
    PATH="$HOME/Applications"
fi
